import { Event, User, Team, CheckIn, Announcement, Rubric, Score } from '../types';
import { generateAttendeeQRToken } from './qrService';

export const SEED_EVENT: Event = {
  id: 'evt-ai-challenge-2026',
  name: 'Global AI Hackathon 2026',
  tagline: 'Build with AI — Next-Gen Real-time Cloud Challenge',
  description: 'The premier national AI & Cloud hackathon bringing together builders, designers, and innovators to create impactful real-time applications on Google Cloud and Gemini AI.',
  dates: {
    start: '2026-08-29T09:00:00.000Z',
    end: '2026-08-30T18:00:00.000Z',
    checkInDeadline: '2026-08-29T12:00:00.000Z',
    judgingLockDeadline: '2026-08-30T16:00:00.000Z',
  },
  location: 'Google Developer Space & Virtual Cloud Hub',
  status: 'active',
  maxTeamSize: 4,
  tags: ['Google Cloud', 'Firebase', 'Gemini AI', 'Real-Time', 'TypeScript'],
};

export const SEED_USERS: User[] = [
  // Organizer
  {
    id: 'user-org-1',
    name: 'Elena Rostova',
    email: 'elena.lead@promptwars.dev',
    role: 'organizer',
    eventId: SEED_EVENT.id,
    skills: ['Operations', 'Community', 'Cloud Architecture'],
    bio: 'Lead Hackathon Organizer & Google Developer Expert.',
    lookingForTeam: false,
    createdAt: '2026-08-20T10:00:00.000Z',
  },
  // Judges
  {
    id: 'user-judge-1',
    name: 'Dr. Marcus Vance',
    email: 'marcus.vance@ai-research.org',
    role: 'judge',
    eventId: SEED_EVENT.id,
    skills: ['LLMs', 'Prompt Engineering', 'Model Evaluation'],
    bio: 'AI Research Director specializing in multimodal foundation models.',
    lookingForTeam: false,
    createdAt: '2026-08-21T10:00:00.000Z',
  },
  {
    id: 'user-judge-2',
    name: 'Sarah Chen',
    email: 'sarah.chen@cloudarch.io',
    role: 'judge',
    eventId: SEED_EVENT.id,
    skills: ['Cloud Architecture', 'Distributed Systems', 'Security'],
    bio: 'Staff Cloud Solutions Architect & Google Cloud Certified Fellow.',
    lookingForTeam: false,
    createdAt: '2026-08-21T11:00:00.000Z',
  },
  {
    id: 'user-judge-3',
    name: 'Devon Kotecha',
    email: 'devon.ux@designcraft.com',
    role: 'judge',
    eventId: SEED_EVENT.id,
    skills: ['Design Systems', 'Web Accessibility (WCAG)', 'Frontend'],
    bio: 'Principal UX Architect & Accessibility Advocate.',
    lookingForTeam: false,
    createdAt: '2026-08-21T12:00:00.000Z',
  },
  // Participants
  {
    id: 'user-part-1',
    name: 'Alex Rivera',
    email: 'alex.rivera@dev.io',
    role: 'participant',
    eventId: SEED_EVENT.id,
    skills: ['React', 'TypeScript', 'Tailwind CSS', 'Vite'],
    desiredRole: 'Frontend',
    bio: 'Frontend enthusiast obsessed with micro-interactions and fast web UX.',
    teamId: 'team-1',
    lookingForTeam: false,
    createdAt: '2026-08-22T08:00:00.000Z',
  },
  {
    id: 'user-part-2',
    name: 'Priya Sharma',
    email: 'priya.sharma@mltech.ai',
    role: 'participant',
    eventId: SEED_EVENT.id,
    skills: ['Python', 'Gemini API', 'PyTorch', 'Vector Databases'],
    desiredRole: 'AI/ML Engineer',
    bio: 'Building autonomous agent workflows and multimodal search engines.',
    teamId: 'team-1',
    lookingForTeam: false,
    createdAt: '2026-08-22T08:30:00.000Z',
  },
  {
    id: 'user-part-3',
    name: 'Liam Zhang',
    email: 'liam.zhang@cloudops.net',
    role: 'participant',
    eventId: SEED_EVENT.id,
    skills: ['Firebase', 'Cloud Functions', 'Node.js', 'WebSockets'],
    desiredRole: 'Backend',
    bio: 'Real-time database engineer & distributed backend tinkerer.',
    teamId: 'team-2',
    lookingForTeam: false,
    createdAt: '2026-08-22T09:00:00.000Z',
  },
  {
    id: 'user-part-4',
    name: 'Sophia Al-Mansoor',
    email: 'sophia.design@studio.co',
    role: 'participant',
    eventId: SEED_EVENT.id,
    skills: ['Figma', 'UI/UX Design', 'Design Systems', 'Tailwind CSS'],
    desiredRole: 'UI/UX Designer',
    bio: 'Designing accessible, high-contrast dark interfaces for modern web tools.',
    teamId: 'team-2',
    lookingForTeam: false,
    createdAt: '2026-08-22T09:30:00.000Z',
  },
  {
    id: 'user-part-5',
    name: 'Kenji Takahashi',
    email: 'kenji.t@agentic.dev',
    role: 'participant',
    eventId: SEED_EVENT.id,
    skills: ['Gemini 2.0', 'LangChain', 'Python', 'FastAPI'],
    desiredRole: 'AI/ML Engineer',
    bio: 'Passionate about structured outputs and agentic workflows.',
    teamId: 'team-3',
    lookingForTeam: false,
    createdAt: '2026-08-22T10:00:00.000Z',
  },
  {
    id: 'user-part-6',
    name: 'Maya Patel',
    email: 'maya.patel@security.org',
    role: 'participant',
    eventId: SEED_EVENT.id,
    skills: ['Cybersecurity', 'Auth Protocols', 'TypeScript', 'Node.js'],
    desiredRole: 'Fullstack',
    bio: 'Fullstack dev with heavy emphasis on zero-trust and RBAC security.',
    teamId: null,
    lookingForTeam: true,
    createdAt: '2026-08-22T11:00:00.000Z',
  },
  {
    id: 'user-part-7',
    name: 'Gabriel Morales',
    email: 'gabriel.m@dataviz.io',
    role: 'participant',
    eventId: SEED_EVENT.id,
    skills: ['Canvas API', 'D3.js', 'React', 'TypeScript'],
    desiredRole: 'Frontend',
    bio: 'Creative coder crafting dynamic 60fps real-time data visualizers.',
    teamId: null,
    lookingForTeam: true,
    createdAt: '2026-08-22T11:30:00.000Z',
  },
  {
    id: 'user-part-8',
    name: 'Amina Nour',
    email: 'amina.nour@ai-product.com',
    role: 'participant',
    eventId: SEED_EVENT.id,
    skills: ['Product Strategy', 'Gemini Prompts', 'Growth', 'User Research'],
    desiredRole: 'Product/Strategy',
    bio: 'Product strategist bridging technical AI capabilities with end-user value.',
    teamId: null,
    lookingForTeam: true,
    createdAt: '2026-08-22T12:00:00.000Z',
  },
];

export const SEED_TEAMS: Team[] = [
  {
    id: 'team-1',
    eventId: SEED_EVENT.id,
    name: 'NeuroPulse AI',
    leaderId: 'user-part-1',
    memberIds: ['user-part-1', 'user-part-2'],
    projectTitle: 'Real-time Autonomous Event Triage with Multimodal Gemini',
    projectDescription: 'Intelligent live event stream processor that monitors attendee feedback, detects venue bottlenecks using vision, and dispatches automated organizer alerts.',
    demoUrl: 'https://neuropulse-ai.web.app',
    repoUrl: 'https://github.com/neuropulse/neuropulse-ai',
    category: 'AI & Real-Time Cloud',
    status: 'forming',
    lookingForRoles: ['Backend', 'UI/UX Designer'],
    createdAt: '2026-08-22T09:00:00.000Z',
    updatedAt: '2026-08-22T09:30:00.000Z',
  },
  {
    id: 'team-2',
    eventId: SEED_EVENT.id,
    name: 'CloudGuardian',
    leaderId: 'user-part-3',
    memberIds: ['user-part-3', 'user-part-4'],
    projectTitle: 'Zero-Trust Attendee Access & Edge Verification System',
    projectDescription: 'Decentralized QR verification running on Cloud Run with biometric anti-spoofing and offline-first edge state sync.',
    demoUrl: 'https://cloudguardian-secure.web.app',
    repoUrl: 'https://github.com/cloudguardian/edge-verify',
    category: 'Security & Infrastructure',
    status: 'locked',
    lookingForRoles: [],
    createdAt: '2026-08-22T10:00:00.000Z',
    updatedAt: '2026-08-22T11:00:00.000Z',
  },
  {
    id: 'team-3',
    eventId: SEED_EVENT.id,
    name: 'EcoSync Hub',
    leaderId: 'user-part-5',
    memberIds: ['user-part-5'],
    projectTitle: 'Smart Carbon & Resource Tracker for Large-Scale Tech Gatherings',
    projectDescription: 'Aggregates smart badge telemetry and food waste data using Gemini models to calculate real-time ESG metrics.',
    demoUrl: 'https://ecosync-hub.web.app',
    repoUrl: 'https://github.com/ecosync/ecosync-platform',
    category: 'Sustainability & AI',
    status: 'forming',
    lookingForRoles: ['Frontend', 'UI/UX Designer', 'Fullstack'],
    createdAt: '2026-08-22T10:30:00.000Z',
    updatedAt: '2026-08-22T10:30:00.000Z',
  },
];

export const SEED_CHECKINS: CheckIn[] = [
  {
    id: 'chk-1',
    userId: 'user-part-1',
    userName: 'Alex Rivera',
    userEmail: 'alex.rivera@dev.io',
    eventId: SEED_EVENT.id,
    qrToken: generateAttendeeQRToken(SEED_EVENT.id, 'user-part-1'),
    checkedInAt: '2026-08-29T09:15:00.000Z',
    method: 'onsite',
    verifiedBy: 'user-org-1',
  },
  {
    id: 'chk-2',
    userId: 'user-part-2',
    userName: 'Priya Sharma',
    userEmail: 'priya.sharma@mltech.ai',
    eventId: SEED_EVENT.id,
    qrToken: generateAttendeeQRToken(SEED_EVENT.id, 'user-part-2'),
    checkedInAt: '2026-08-29T09:20:00.000Z',
    method: 'onsite',
    verifiedBy: 'user-org-1',
  },
  {
    id: 'chk-3',
    userId: 'user-part-3',
    userName: 'Liam Zhang',
    userEmail: 'liam.zhang@cloudops.net',
    eventId: SEED_EVENT.id,
    qrToken: generateAttendeeQRToken(SEED_EVENT.id, 'user-part-3'),
    checkedInAt: '2026-08-29T09:25:00.000Z',
    method: 'virtual',
    verifiedBy: 'user-org-1',
  },
];

export const SEED_RUBRIC: Rubric = {
  id: 'rubric-promptwars-main',
  eventId: SEED_EVENT.id,
  name: 'Standard Hackathon Evaluation Rubric',
  aggregationMethod: 'weighted_average',
  criteria: [
    {
      id: 'crit-innovation',
      name: 'Innovation & Problem Statement Alignment',
      description: 'How novel, creative, and aligned is the solution to real-world event pain points?',
      maxScore: 10,
      weight: 1.2,
    },
    {
      id: 'crit-tech-realtime',
      name: 'Technical Execution & Real-Time Sync',
      description: 'Quality of architecture, performance, reactive live listeners, zero polling, and robustness.',
      maxScore: 10,
      weight: 1.5,
    },
    {
      id: 'crit-google-services',
      name: 'Google Cloud & Gemini AI Integration',
      description: 'Effective use of Firebase, Google Cloud Hosting/Run, and Gemini API for intelligence.',
      maxScore: 10,
      weight: 1.3,
    },
    {
      id: 'crit-ui-a11y',
      name: 'UI/UX Design, Polish & Accessibility',
      description: 'Visual aesthetics, responsive layout, semantic markup, keyboard accessibility, and micro-interactions.',
      maxScore: 10,
      weight: 1.0,
    },
  ],
  updatedAt: '2026-08-20T12:00:00.000Z',
};

export const SEED_SCORES: Score[] = [
  {
    id: 'score-1-judge1',
    eventId: SEED_EVENT.id,
    teamId: 'team-1',
    teamName: 'NeuroPulse AI',
    judgeId: 'user-judge-1',
    judgeName: 'Dr. Marcus Vance',
    rubricId: SEED_RUBRIC.id,
    criterionScores: [
      { criterionId: 'crit-innovation', criterionName: 'Innovation & Problem Statement Alignment', score: 9.5, maxScore: 10, weight: 1.2 },
      { criterionId: 'crit-tech-realtime', criterionName: 'Technical Execution & Real-Time Sync', score: 9.0, maxScore: 10, weight: 1.5 },
      { criterionId: 'crit-google-services', criterionName: 'Google Cloud & Gemini AI Integration', score: 9.8, maxScore: 10, weight: 1.3 },
      { criterionId: 'crit-ui-a11y', criterionName: 'UI/UX Design, Polish & Accessibility', score: 8.5, maxScore: 10, weight: 1.0 },
    ],
    totalScore: 92.2,
    feedback: 'Outstanding prompt orchestrations and very low latency event handling. Great integration with Gemini.',
    submittedAt: '2026-08-30T14:30:00.000Z',
    locked: true,
    auditTrail: [
      { timestamp: '2026-08-30T14:20:00.000Z', action: 'created', totalComputedScore: 90.0, judgeId: 'user-judge-1' },
      { timestamp: '2026-08-30T14:30:00.000Z', action: 'locked', totalComputedScore: 92.2, judgeId: 'user-judge-1' },
    ],
  },
  {
    id: 'score-2-judge1',
    eventId: SEED_EVENT.id,
    teamId: 'team-2',
    teamName: 'CloudGuardian',
    judgeId: 'user-judge-1',
    judgeName: 'Dr. Marcus Vance',
    rubricId: SEED_RUBRIC.id,
    criterionScores: [
      { criterionId: 'crit-innovation', criterionName: 'Innovation & Problem Statement Alignment', score: 8.5, maxScore: 10, weight: 1.2 },
      { criterionId: 'crit-tech-realtime', criterionName: 'Technical Execution & Real-Time Sync', score: 9.5, maxScore: 10, weight: 1.5 },
      { criterionId: 'crit-google-services', criterionName: 'Google Cloud & Gemini AI Integration', score: 8.8, maxScore: 10, weight: 1.3 },
      { criterionId: 'crit-ui-a11y', criterionName: 'UI/UX Design, Polish & Accessibility', score: 9.0, maxScore: 10, weight: 1.0 },
    ],
    totalScore: 89.8,
    feedback: 'Exceptional architectural resilience and security posture. Clean zero-trust implementation.',
    submittedAt: '2026-08-30T14:45:00.000Z',
    locked: true,
    auditTrail: [
      { timestamp: '2026-08-30T14:45:00.000Z', action: 'locked', totalComputedScore: 89.8, judgeId: 'user-judge-1' },
    ],
  },
  {
    id: 'score-1-judge2',
    eventId: SEED_EVENT.id,
    teamId: 'team-1',
    teamName: 'NeuroPulse AI',
    judgeId: 'user-judge-2',
    judgeName: 'Sarah Chen',
    rubricId: SEED_RUBRIC.id,
    criterionScores: [
      { criterionId: 'crit-innovation', criterionName: 'Innovation & Problem Statement Alignment', score: 9.0, maxScore: 10, weight: 1.2 },
      { criterionId: 'crit-tech-realtime', criterionName: 'Technical Execution & Real-Time Sync', score: 9.2, maxScore: 10, weight: 1.5 },
      { criterionId: 'crit-google-services', criterionName: 'Google Cloud & Gemini AI Integration', score: 9.5, maxScore: 10, weight: 1.3 },
      { criterionId: 'crit-ui-a11y', criterionName: 'UI/UX Design, Polish & Accessibility', score: 8.8, maxScore: 10, weight: 1.0 },
    ],
    totalScore: 91.5,
    feedback: 'Very scalable Firestore queries and composite index design. Subscriptions clean up properly.',
    submittedAt: '2026-08-30T15:00:00.000Z',
    locked: false,
    auditTrail: [
      { timestamp: '2026-08-30T15:00:00.000Z', action: 'created', totalComputedScore: 91.5, judgeId: 'user-judge-2' },
    ],
  },
];

export const SEED_ANNOUNCEMENTS: Announcement[] = [
  {
    id: 'ann-1',
    eventId: SEED_EVENT.id,
    authorId: 'user-org-1',
    authorName: 'Elena Rostova',
    authorRole: 'organizer',
    title: '🚀 Welcome to the Hackathon! Kickoff & Schedule',
    body: 'The hacking period is now officially OPEN! Review the event rubric in the Judging tab, lock in your team rosters by 12:00 PM, and join the mentor desk for real-time architecture feedback.',
    severity: 'info',
    category: 'Schedule',
    createdAt: '2026-08-29T09:00:00.000Z',
    pinned: true,
  },
  {
    id: 'ann-2',
    eventId: SEED_EVENT.id,
    authorId: 'user-org-1',
    authorName: 'Elena Rostova',
    authorRole: 'organizer',
    title: '⚡ Check-in Desk & Badge Verification Active',
    body: 'Please have your digital QR Pass ready in your Participant dashboard. Organizers are scanning at Main Atrium Entrance and Virtual Verify Desk.',
    severity: 'warning',
    category: 'Venue',
    createdAt: '2026-08-29T09:30:00.000Z',
  },
  {
    id: 'ann-3',
    eventId: SEED_EVENT.id,
    authorId: 'user-org-1',
    authorName: 'Elena Rostova',
    authorRole: 'organizer',
    title: '🔥 Live Judging Protocol & Scoring Window Opened',
    body: 'Judges Marcus Vance, Sarah Chen, and Devon Kotecha have begun preliminary project assessments. Teams can monitor the live leaderboard in real time.',
    severity: 'critical',
    category: 'Judging',
    createdAt: '2026-08-29T14:00:00.000Z',
  },
];
